spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
server:
  port: 8081
